import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f6faff",
        "surface-dim": "#cfdce7",
        "surface-bright": "#f6faff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ebf5ff",
        "surface-container": "#e3effb",
        "surface-container-high": "#ddeaf5",
        "surface-container-highest": "#d8e4f0",
        "on-surface": "#111d25",
        "on-surface-variant": "#534249",
        "inverse-surface": "#26323b",
        "inverse-on-surface": "#e6f2fe",
        outline: "#867279",
        "outline-variant": "#d8c0c9",
        "surface-tint": "#9c3a70",
        primary: "#9c3a70",
        "on-primary": "#ffffff",
        "primary-container": "#ff8cc6",
        "on-primary-container": "#7a1e55",
        "inverse-primary": "#ffafd4",
        secondary: "#006780",
        "on-secondary": "#ffffff",
        "secondary-container": "#5ed8ff",
        "on-secondary-container": "#005c72",
        tertiary: "#785a00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d6ac45",
        "on-tertiary-container": "#574100",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffd8e7",
        "primary-fixed-dim": "#ffafd4",
        "on-primary-fixed": "#3d0026",
        "on-primary-fixed-variant": "#7e2158",
        "secondary-fixed": "#b7eaff",
        "secondary-fixed-dim": "#5bd5fc",
        "on-secondary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#004e61",
        "tertiary-fixed": "#ffdf9b",
        "tertiary-fixed-dim": "#edc157",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary-fixed-variant": "#5b4300",
        background: "#f6faff",
        "on-background": "#111d25",
        "surface-variant": "#d8e4f0",
      },
      fontFamily: {
        "headline-xl": ["var(--font-jakarta)", "sans-serif"],
        "headline-lg": ["var(--font-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-vietnam)", "sans-serif"],
        "body-md": ["var(--font-vietnam)", "sans-serif"],
        "label-lg": ["var(--font-vietnam)", "sans-serif"],
      },
      fontSize: {
        "headline-xl": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
